In [21]:
dataset=[]

In [3]:
import numpy as np
import cv2

In [19]:
import random

In [20]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [24]:
for i in range(10):
    n=random.randint(1,4000)
    img1=cv2.imread("training_set/training_set/cats/cat."+str(n)+".jpg")
    img2=cv2.imread("training_set/training_set/dogs/dog."+str(n)+".jpg") 
    
    img1=cv2.resize(img1,(500,500))
    img2=cv2.resize(img2,(500,500))
    
    img1=np.array(img1).flatten()
    img2=np.array(img2).flatten()
    
    dataset.append(img1)
    dataset.append(img2)
    

In [44]:
test_X=[]
for i in range(10):
    n=random.randint(4001,5000)
    img1=cv2.imread("test_set/test_set/cats/cat."+str(n)+".jpg")
    img2=cv2.imread("test_set/test_set/dogs/dog."+str(n)+".jpg") 
    
    img1=cv2.resize(img1,(500,500))
    img2=cv2.resize(img2,(500,500))
    
    img1=np.array(img1).flatten()
    img2=np.array(img2).flatten()
    
    test_X.append(img1)
    test_X.append(img2)
    

In [26]:
len(dataset)

20

In [29]:
res=[0,1]*10 #0 for Cat and 1 for Dog

In [38]:
x_train=dataset
y_train=res
test_Y=res

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
lr = LogisticRegression()

C:\Users\karti\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(dataset, res, test_size=0.25, random_state=42)

In [51]:
lr.fit(X_train, y_train)

C:\Users\karti\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [63]:
score = lr.score(X_train, y_train)
print(score)

1.0


In [52]:
score = lr.score(X_test, y_test)
print(score)

0.6


In [53]:
sizes=[(100,100),(50,50),(25,25),(10,10)]

In [64]:
for i in sizes :
    dataset=[]
    for j in range(10):
        n=random.randint(1,4000)
        img1=cv2.imread("training_set/training_set/cats/cat."+str(n)+".jpg")
        img2=cv2.imread("training_set/training_set/dogs/dog."+str(n)+".jpg") 

        img1=cv2.resize(img1,i)
        img2=cv2.resize(img2,i)

        img1=np.array(img1).flatten()
        img2=np.array(img2).flatten()

        dataset.append(img1)
        dataset.append(img2)
        
    res=[0,1]*10
    X_train, X_test, y_train, y_test = train_test_split(dataset, res, test_size=0.25, random_state=42)
    lr.fit(X_train, y_train)
    print("Train Score for ",i,"=",lr.score(X_train, y_train))
    print("Test Score for ",i,"=",lr.score(X_test, y_test))
    print()

C:\Users\karti\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\karti\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\karti\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train Score for  (100, 100) = 1.0
Test Score for  (100, 100) = 0.8

Train Score for  (50, 50) = 1.0
Test Score for  (50, 50) = 0.4

Train Score for  (25, 25) = 1.0
Test Score for  (25, 25) = 0.8

Train Score for  (10, 10) = 1.0
Test Score for  (10, 10) = 0.6



C:\Users\karti\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
